# Generated by Django 4.2.6 on 2023-10-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
