# Generated by Django 4.2.6 on 2023-11-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_count_series_card_duration_movies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='duration_movies',
            new_name='duration_all',
        ),
    ]
