# Generated by Django 4.2.6 on 2023-11-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_rename_duration_movies_card_duration_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='kp_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
