# Generated by Django 4.2.6 on 2023-11-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_kp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='kp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
